version: '3'
services:
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:3.3.0
    container_name: ${CONTAINER_NAME}
    volumes:
      - forgejo-runner-data:/data
    command: "forgejo-runner --config config.yml daemon"
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network

volumes:
  forgejo-runner-data:
    external: true

networks:
  1panel-network:
    external: true