version: '3'
services:
  mautrix-telegram:
    image: dock.mau.dev/mautrix/telegram:v0.15.1
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - mautrix_telegram_data:/data:z
    labels:
      createdBy: "Apps"
volumes:
  mautrix_telegram_data:
    external: true
networks:
  1panel-network:
    external: true
